#!/bin/bash

install_aws_cli() {
    read -rp "[PROMPT] Do you want to install AWS CLI? (y/n): " choice

    # Convert input to lowercase for case-insensitive comparison
    choice=$(echo "$choice" | tr '[:upper:]' '[:lower:]')

    # Check the user's choice and proceed accordingly
    if [[ "$choice" == "y" || "$choice" == "yes" ]]; then
        if ! command -v curl &> /dev/null; then
            echo "[ERROR] 'curl' command not found. Please install curl and run the script again."
            exit 1
        fi

        if ! command -v unzip &> /dev/null; then
            echo "[ERROR] 'unzip' command not found. Please install unzip and run the script again."
            exit 1
        fi

        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        ./aws/install || {
            echo "[ERROR] Failed to install AWS CLI. Exiting..."
            exit 1
        }

        echo "[INFO] AWS CLI installed successfully."

        # Clean up downloaded files
        rm awscliv2.zip
        rm -rf aws

    elif [[ "$choice" == "n" || "$choice" == "no" ]]; then
        echo "[INFO] Not installing AWS CLI and continuing..."
    else
        echo "[ERROR] Invalid choice. Please enter 'y' or 'n' for yes or no respectively."
        exit 1
    fi
}

install_aws_cli
